## Introducción a PyTorch (Parte 1)

<a target="_blank" href="https://colab.research.google.com/github/pglez82/DeepLearningWeb/blob/master/labs/notebooks/Introducci%C3%B3n%20a%20PyTorch%20(Parte%201).ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

PyTorch es un framework de aprendizaje profundo desarrollado por Facebook, de **código abierto** y con contribuciones de miles de usuarios. Es una alternativa a otros frameworks como TensorFlow o MXNet. El lenguaje de programación utilizado por este framework es Python (aunque muchas de sus partes están programas en otros lenguajes como C++). En este tutorial, vamos a aprender los fundamentos de PyTorch para que puedas utilizarlo en el resto de prácticas.



#### Primeros pasos
Lo primero consiste en ver si tenemos PyTorch instalado y conocer su versión:

In [1]:
import torch
print(torch.__version__)

2.12.0+cpu


si en la salida anterior ves **cpu** será que estás ejecutando una compilación de PyTorch solo con soporte para CPU y no GPU. Si por el contrario quieres ejecutar PyTorch en una máquina con GPU como Google Colab (o incluso tu propia máquina con GPU y Cuda instalado), la salida de este comando debería indicartelo. Ten en cuenta que la versión con GPU también soporta entrenamientos en la CPU (lo contrario no es cierto).

Un aspecto importante en los experimentos que hagamos será la reproducibilidad de resultados. Establecemos una semilla para que todos los números aleatorios generados sean los mismos ejecución tras ejecución:

In [2]:
torch.manual_seed(2032)

#### Tensores

Los tensores son la pieza clave en cualquier framework de aprendizaje profundo. Son equivalentes a los arrays de Numpy pero tienen ciertas diferencias muy importantes:

1. Los tensores **pueden moverse entre diferentes dispositivos**. Es decir, podemos tener un tensor en CPU y moverlo a la GPU y todos los cálculos realizados con este pasarán a realizarse en este dispositivo.
2. Los tensores están preparados para diferenciar sobre ellos (calcular las derivadas parciales necesarias para aplicar descenso de gradiente). 

De todas maneras, una de las principales ventajas de PyTorch es que si sabemos operar con arrays de Numpy, cambiar a hacerlo con tensores será muy sencillo. Vamos a crear nuestro primer Tensor:

In [3]:
x = torch.Tensor(3, 4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


aquí tenemos un tensor de 3x4 de números reales, inicializado con los valores que estén en memoria en ese momento.

Podemos mostrar su dimensión:

In [4]:
print(x.shape)

torch.Size([3, 4])


También es posible inicializar tensores con otros valores, como por ejemplo, ceros, unos o valores aleatorios entre 0 y 1:

In [5]:
print(torch.zeros(3,4))
print(torch.ones(3,4))
print(torch.rand(3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.6282, 0.7710, 0.5404, 0.5480],
        [0.0920, 0.3038, 0.9887, 0.5169],
        [0.7733, 0.7820, 0.8844, 0.8440]])


Otra manera de crear un tensor es hacerlo desde un array de numpy existente:

In [6]:
import numpy as np
np_arr = np.array([[1, 2], [3, 4]])
tensor = torch.from_numpy(np_arr)
print(tensor)
print(tensor.shape)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


En este case se pude ver que como el array era de números enteros, el tensor resultante mantiene este tipo. Siempre podemos ver el **tipo de los elementos de un tensor** con la siguiente instrucción:

In [7]:
print(tensor.dtype)

torch.int64


Ten en cuenta que **el tipo es crítico** ya que nuestra red va a requerir muchísimos parámetros que al final van a ser tensores y la memoria de nuestros dispositivos es limitada. Te recomiendo el siguiente [enlace](https://pytorch.org/docs/stable/tensors.html) para conocer los diferentes tipos y saber cuando ocupa cada uno en memoria.

Además de crear tensores, muchas veces es interesante convertirlos de vuelta a Numpy. Podemos hacerlo de la siguiente manera:

In [8]:
tensor.cpu().numpy()

array([[1, 2],
       [3, 4]])

Ten en cuenta que la llamada cpu() lo que hace es mover el tensor a la cpu (si no está ya). Es importante hacer esta llamada porque para pasar el tensor a numpy tiene que estar en cpu primero.

Para mover tensores de un dispositivo a otro podemos hacerlo de la siguiente manera.

In [9]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
tensor = tensor.to(device)

obviamente para que esto funcione debemos tener PyTorch instalado con soporte para cuda (sino el tensor se quedará en la cpu). En este caso **cuda:0** indica que queremos mover el tensor a la primera GPU del sistema. Es importante tener en cuenta que `tensor.to` devuelve el tensor en el nuevo dispositivo por tanto debemos recordar guardarlo en una variable para posteriormente poder usarlo.

#### Operaciones con tensores

Existen multitud de operaciones que se pueden realizar con tensores. En el siguiente [enlace](https://pytorch.org/docs/stable/tensors.html#) tienes una descripción completa de todas las operaciones que se pueden realizar. Aquí vamos a describir las más básicas.

In [10]:
t1 = torch.rand(3,2)
t2 = torch.rand(3,2)
suma = t1+t2
print(t1)
print(t2)
print(suma)

tensor([[0.6985, 0.2108],
        [0.1112, 0.1474],
        [0.8116, 0.1859]])
tensor([[0.5345, 0.4596],
        [0.3705, 0.5302],
        [0.5715, 0.7342]])
tensor([[1.2330, 0.6704],
        [0.4817, 0.6776],
        [1.3831, 0.9201]])


ten en cuenta que esta operación crea un nuevo tensor en memoria. En PyTorch es posible también realizar **operaciones sobre los mismos tensores**, para no gastar espacio extra en memoria. Por ejemplo:

In [11]:
t2.add_(t1)

tensor([[1.2330, 0.6704],
        [0.4817, 0.6776],
        [1.3831, 0.9201]])

Tenemos otras operaciones disponibles pero en general, **las operaciones básicas que puedes hacer con Numpy también se pueden hacer con tensores**:

In [12]:
t1 = torch.rand(3,2)
t2 = torch.rand(3,2)
print(t1)
print(t2)
print("Resta:")
print(t1-t2)
print("Multiplicación por un escalar:")
print(t1*3)
print("Multiplicación de matrices elemento a elemento:")
print(t1*t2)
print("Multiplicación de matrices normal:")
#Importante: estamos haciendo la transpuesta de t2 para poder multiplicarlas y que coincidan las dimesiones
print(t1@t2.T)

tensor([[0.4333, 0.4734],
        [0.1678, 0.0093],
        [0.9842, 0.3493]])
tensor([[0.5617, 0.6045],
        [0.8110, 0.5253],
        [0.3047, 0.6035]])
Resta:
tensor([[-0.1284, -0.1311],
        [-0.6432, -0.5160],
        [ 0.6795, -0.2542]])
Multiplicación por un escalar:
tensor([[1.2999, 1.4201],
        [0.5034, 0.0278],
        [2.9526, 1.0479]])
Multiplicación de matrices elemento a elemento:
tensor([[0.2434, 0.2861],
        [0.1361, 0.0049],
        [0.2999, 0.2108]])
Multiplicación de matrices normal:
tensor([[0.5295, 0.6001, 0.4177],
        [0.0999, 0.1410, 0.0567],
        [0.7640, 0.9817, 0.5107]])


#### Cambio de la forma de un tensor

En muchas ocasiones necesitamos cambiar la forma de un tensor, para luego poder operar con él correctamente. Para esto es muy adecuada la función **view**:

In [13]:
#arange crea un tensor con valores desde 0 hasta n-1
t1 = torch.arange(10)
print(t1)

#digamos que queremos una matriz de 5x2
print(t1.view(5,2))

#También podemos inferir dimensiones
print(t1.view(5,-1))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


es interesante entender que view devuelve un nuevo tensor pero que comparte la estructura interna con el tensor original, es decir, no estamos almacenando los datos de nuevo, sino simplemente **dándoles otra forma**.

#### Indexado
El indexado funciona de igual manera que en Numpy. Veamos algunos ejemplos:

In [14]:
t1 = torch.arange(12).view(3,4)
print(t1)

print("Solo la segunda fila (empieza a contar en cero):")
print(t1[1,:])
print("Solo la última columna:")
print(t1[:,-1])
print("Seleccionar el primer elemento de las dos primeras filas:")
print(t1[:2,0])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Solo la segunda fila (empieza a contar en cero):
tensor([4, 5, 6, 7])
Solo la última columna:
tensor([ 3,  7, 11])
Seleccionar el primer elemento de las dos primeras filas:
tensor([0, 4])


### Ejercicios propuestos

1. Descarga la documentación de PyTorch del campus virtual y busca las siguientes funciones:
   - clamp: ¿Para qué sirve? Aplícala sobre un tensor generado con torch.randn.
   - squeeze y unsqueeze: Crea un tensor de tamaño (3,) y utiliza estas funciones para transformarlo primero en (1, 3, 1) y luego volver a dejarlo en (3,).
2. ¿En qué dispositivo se está ejecutando el notebook por defecto?
3. Ejecuta el notebook en local, comprueba que todos los tensores están en la CPU.
4. Intenta realizar una operación con dos tensores que se encuentren en dispositivos diferentes. ¿Qué sucede en este caso?
5. Realiza las siguientes operaciones con tensores:
   - Crear Tensores: Crea los siguientes tensores en PyTorch:
      - Un tensor *t_1* de 10 elementos igualmente espaciados entre 0 y 1.
      - Un tensor *t_2* de tamaño 3x3 con valores aleatorios.
      - Un tensor *t_3* de tamaño 2x3x4 con todos sus elementos inicializados a 1.
   - Extrae la segunda fila del tensor *t_2*.
   - Cambia la forma (reshape) de *t_3* a un tensor 2D de tamaño 6x4.
   - Transpón el tensor *t_2* (intercambia filas por columnas).
   - Suma el tensor [1.0, 1.0, 1.0] a la primera fila de *t_2*.
   - Realiza un producto elemento a elemento entre *t_2* y su transpuesta.
   - Realiza un producto matricial entre *t_2* y su transpuesta.
   - Selecciona todos los elementos de la *t_2* que sean mayores que 0.5.
   - Crea un tensor booleano de la misma forma que el *t_2*, que sea True si el elemento es mayor que 0.5, y False en caso contrario.
   - Cuenta cuantos elementos de *t_2* son mayores de que la media de los elementos de *t_2*.


In [15]:
#EJERCICIO1 
# clamp --> todo elemento del tensor que no esté dentro del rango establecido en (min,max) será reemplazado
# por min si es menor que min y por max si es mayor que max 
tensor = torch.randn(4)
print(tensor)
tensor_clamp = tensor.clamp(min = -1,max = 1)
print(tensor_clamp)
tensor == tensor_clamp

#squeeze y unsqueeze
tensor1 = torch.tensor([1,2,3])
print(tensor1,tuple(tensor1.shape))
#unsqueeze --> retorna un nuevo tensor con la dimensión actualizada poniendo un 1 en la posición indicada, 
# empieza en 0
tensor2 = tensor1.unsqueeze(0)
print(tensor2,tuple(tensor2.shape))
tensor3 = tensor2.unsqueeze(2)
print(tensor3,tuple(tensor3.shape))
#squeeze -> retorna un tensor quitando todas las dimensiones 1
tensor4 = tensor3.squeeze()
print(tensor4,tuple(tensor4.shape))

#EJERCICIO2

tensor = torch.tensor([1,2,3])
tensor.device


#EJERCICIO3

lista_tensores = [tensor1,tensor2,tensor3,tensor4]

for i in lista_tensores : 
    print(i.device)


    #EJERCICIO4

t1 = torch.randn(3)
t2 = torch.randn(3)
print(t1 + t2)

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
t2 = t2.to(device)
print(f"Ahora la operacion t1 + t2 daría error ya que t2 se encuentra en un dispositivo diferente")
print(f"El dispositivo en el que se encuentra t2 es {t2.device} y el de t1 es {t1.device}")


#EJERCICIO5
#a
t_1 = torch.linspace(0,1,10)
print(t_1)
t_2 = torch.rand(3,3)
print(t_2)
t_3 = torch.ones(2,3,4)
print(t_3)
#b

print("·La segunda fila del tensor t_2")
print(t_2[1])

#c
t_3 = t_3.reshape(6,-1)
print("·Tensor t_3 con dimensiones 6x4")
print(t_3)

#d
print("·El tensor t_2 transpuesto")
print(t_2.transpose(0,1))

#e
t_unos = torch.ones(1,3)
print(t_unos)
print("·Suma de vector de unos y la segunda fila de t_2")
print(t_unos + t_2[1])

#f
print("Multiplicación entre t_2 y su transpuesta")
print(t_2 * t_2.transpose(0,1))

tensor([ 0.6535, -0.7494,  0.0911,  1.6559])
tensor([ 0.6535, -0.7494,  0.0911,  1.0000])
tensor([1, 2, 3]) (3,)
tensor([[1, 2, 3]]) (1, 3)
tensor([[[1],
         [2],
         [3]]]) (1, 3, 1)
tensor([1, 2, 3]) (3,)
cpu
cpu
cpu
cpu
tensor([-0.2522,  0.9745, -0.4595])
Ahora la operacion t1 + t2 daría error ya que t2 se encuentra en un dispositivo diferente
El dispositivo en el que se encuentra t2 es cpu y el de t1 es cpu
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])
tensor([[0.4427, 0.0484, 0.4585],
        [0.9910, 0.8763, 0.1658],
        [0.3221, 0.6155, 0.5717]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
·La segunda fila del tensor t_2
tensor([0.9910, 0.8763, 0.1658])
·Tensor t_3 con dimensiones 6x4
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        